### ISSUE TITLE
The RST parser tries to parse roman numerals where they aren't

### ISSUE THREAD

**Issue by drewhk** [planet42/Laika#19]
The following line in an rst document

    2. implicit argument of type :class:`akka.util.Timeout`, e.g.

Results in the following error

    java.lang.IllegalArgumentException: Illegal ordering of symbols: IM
    at laika.util.RomanNumerals$.convert$1(RomanNumerals.scala:73) 
    at laika.util.RomanNumerals$.convert$1(RomanNumerals.scala:74)
    at laika.util.RomanNumerals$.romanToInt(RomanNumerals.scala:80)
    at laika.parse.rst.ListParsers$$anonfun$5.apply(ListParsers.scala:89)
    at laika.parse.rst.ListParsers$$anonfun$5.apply(ListParsers.scala:89)
    at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
    at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:135)

although there are no roman numerals involved

**Comment by drewhk** [comment]
Thanks!
