### ISSUE TITLE
IllegalArgumentException: Illegal ordering of symbols: IM

### ISSUE THREAD

**Issue by sirthias** [planet42/Laika#26]
Laika 0.5.1 dies on this ReST document:

```
{%
%}

IMPRESSUM
=========

blah
```

This is the exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal ordering of symbols: IM
  at laika.util.RomanNumerals$.convert$1(RomanNumerals.scala:73)
  at laika.util.RomanNumerals$.convert$1(RomanNumerals.scala:74)
  at laika.util.RomanNumerals$.romanToInt(RomanNumerals.scala:80)
  at laika.parse.rst.ListParsers$$anonfun$7.apply(ListParsers.scala:92)
  at laika.parse.rst.ListParsers$$anonfun$7.apply(ListParsers.scala:92)
  at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:137)
  at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
  at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
  at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
  at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
```

**Comment by jenshalm** [comment]
This looks like a duplicate of #19. It has been fixed quite a while ago, but unfortunately I did not cherry-pick it into the 0.5.1 release, which was branched off of 0.5.0 as the 0.6 work wasn't in a state yet for cutting a release.

Normally it is not recommended to use Laika snapshots, as it is often a bumpy ride between releases in the 0.x phase, but the 0.6 release is nearly done and the only code changes from now on will be bug fixes. As long as you don't use the new features yet (PDF, XSL-FO) where the test suites are not fully complete yet, you should be fine.

**Comment by sirthias** [comment]
Yes, I can confirm that this issue is not present anymore with the current master.
Thanks!
