### ISSUE TITLE
rst - `&A` in title causes `The reference to entity "A" must end with the ';' delimiter.` in pdf output

### ISSUE THREAD

**Issue by aborg0** [planet42/Laika#49]
Steps to reproduce:

1. create a file in `src/docs`, for example `and.rst` (and add Laika 0.6.0 to an sbt 0.13.15 project)
1. add the following content:

    `Q&A`
     `===`

The result of `laika:generate pdf`:

    [error] (root/laika:generate) javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 24; columnNumber: 29; The reference to entity "A" must end with the ';' delimiter.

Details:

    javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 24; columnNumber: 29; The reference to entity "A" must end with the ';' delimiter.
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:749)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:351)
        at laika.render.PDF.renderPDF(PDF.scala:153)
        at laika.render.PDF.process(PDF.scala:108)
        at laika.api.Render$RenderGatheredOutput$$anon$3.renderBinary(Render.scala:399)
        at laika.api.Render$BinaryTarget$class.toFile(Render.scala:230)
        at laika.api.Render$RenderGatheredOutput$$anon$3.toFile(Render.scala:398)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6$$anonfun$59$$anonfun$60.apply(LaikaSbtPlugin.scala:343)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6$$anonfun$59$$anonfun$60.apply(LaikaSbtPlugin.scala:295)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6$$anonfun$59.apply(LaikaSbtPlugin.scala:353)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6$$anonfun$59.apply(LaikaSbtPlugin.scala:293)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6.apply(LaikaSbtPlugin.scala:293)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6.apply(LaikaSbtPlugin.scala:269)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: org.xml.sax.SAXParseException; lineNumber: 24; columnNumber: 29; The reference to entity "A" must end with the ';' delimiter.
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:641)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:737)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:351)
        at laika.render.PDF.renderPDF(PDF.scala:153)
        at laika.render.PDF.process(PDF.scala:108)
        at laika.api.Render$RenderGatheredOutput$$anon$3.renderBinary(Render.scala:399)
        at laika.api.Render$BinaryTarget$class.toFile(Render.scala:230)
        at laika.api.Render$RenderGatheredOutput$$anon$3.toFile(Render.scala:398)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6$$anonfun$59$$anonfun$60.apply(LaikaSbtPlugin.scala:343)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6$$anonfun$59$$anonfun$60.apply(LaikaSbtPlugin.scala:295)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6$$anonfun$59.apply(LaikaSbtPlugin.scala:353)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6$$anonfun$59.apply(LaikaSbtPlugin.scala:293)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6.apply(LaikaSbtPlugin.scala:293)
        at laika.sbt.LaikaSbtPlugin$Tasks$$anonfun$57$$anonfun$apply$5$$anonfun$apply$6.apply(LaikaSbtPlugin.scala:269)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Possible workaround: use `Q&amp;A` instead, though that is rendered as is in HTML, so not so nice.

**Comment by jenshalm** [comment]
Changed the title as the issue is not specific to rst. It is a bug in the renderer and happens with any title, no matter which markup format had been used.
