### ISSUE TITLE
Unicode references above 00FF in rst are not supported: `java.nio.charset.UnmappableCharacterException: Input length = 1`

### ISSUE THREAD

**Issue by aborg0** [planet42/Laika#50]
Steps to reproduce:

1. create a file in `src/docs`, for example `and.rst` (and add Laika 0.6.0 to an sbt 0.13.15 project)
1. add the following content:

`.. |amacron| unicode:: U+0100 .. capital a with macron`
`|amacron|`

The result of `laika:site`:

    [error] (root/laika:copyPDF) java.nio.charset.UnmappableCharacterException: Input length = 1
    [error] (root/laika:site) java.nio.charset.UnmappableCharacterException: Input length = 1

The result of `laika:generate html`:

    [error] (root/laika:generate) java.nio.charset.UnmappableCharacterException: Input length = 1

Details (of `laika:site`):

    java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
        at java.io.BufferedWriter.close(BufferedWriter.java:265)
        at laika.io.Output$AutocloseStreamOutput.close(Output.scala:147)
        at laika.io.Output$LazyFileOutput.close(Output.scala:158)
        at laika.io.IO$.apply(IO.scala:35)
        at laika.api.Render.render(Render.scala:150)
        at laika.api.Render$$anonfun$laika$api$Render$$renderTree$1$1.apply$mcV$sp(Render.scala:178)
        at laika.api.Render$$anonfun$render$2.apply(Render.scala:201)
        at laika.api.Render$$anonfun$render$2.apply(Render.scala:201)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:975)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:972)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:172)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:514)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:162)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
        at java.io.BufferedWriter.close(BufferedWriter.java:265)
        at laika.io.Output$AutocloseStreamOutput.close(Output.scala:147)
        at laika.io.Output$LazyFileOutput.close(Output.scala:158)
        at laika.io.IO$.apply(IO.scala:35)
        at laika.api.Render.render(Render.scala:150)
        at laika.api.Render$$anonfun$laika$api$Render$$renderTree$1$1.apply$mcV$sp(Render.scala:178)
        at laika.api.Render$$anonfun$render$2.apply(Render.scala:201)
        at laika.api.Render$$anonfun$render$2.apply(Render.scala:201)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:975)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:972)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:172)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:514)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:162)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Unfortunately using the unicode symbols instead do not work either. For a single character `λ` content, the result is similar. (With or without specifying the `UTF-8` encoding as `inConfig(LaikaKeys.Laika)(Seq(LaikaKeys.encoding := "UTF-8"))`)

**Comment by aborg0** [comment]
Interestingly this works well in the webtool (which seems to use an older version of laika, maybe 0.3.0?):

    List predicate (Scheme)
    -----------------------
    ::
    
      (def list?
        (λ (l)
          (cond
           ((null? l))
           ((pair? l)
            (list? (cdr l)))
           (else #f))))
    
    A list is either an empty list, or a pair whose tail is a list
    
    Syntax: equality
    ----------------
    
    In Scheme, (≡ x y) is the goal that unifies *x* and *y*; (≢ x y)
    constrains them from being unifiable. The syntax looks natural in
    Scheme, as everything is infix.

Output is:

    <h1>List predicate (Scheme)</h1>
    <pre><code>(def list?
      (λ (l)
        (cond
         ((null? l))
         ((pair? l)
          (list? (cdr l)))
         (else #f))))</code></pre>
    <p>A list is either an empty list, or a pair whose tail is a list</p>
    
    <h1>Syntax: equality</h1>
    <p>In Scheme, (≡ x y) is the goal that unifies <em>x</em> and <em>y</em>; (≢ x y)
    constrains them from being unifiable. The syntax looks natural in
    Scheme, as everything is infix.</p>

**Comment by jenshalm** [comment]
I don't think the version makes a difference. If you look at the stacktrace it happens during rendering, so the parsing works probably just fine. The webtool only writes to an in-memory string, so no encoding required. My gut feeling is that there is just one place left where the specified encoding gets lost before the OutputStream is created. The code path is different for writing a single file and for writing an entire directory and (I think) the unit tests for encoding only assert the former.

I will look into this soonish, sadly, like your other ticker it's too late for the 0.7.0 release which is already in progress.
